version: '3.8'

services:
  proxy:
    image: nginx:1.21-alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/av.com.crt:/etc/nginx/av.com.crt
      - ./nginx/av.com.key:/etc/nginx/av.com.key
      - ./nginx/sso.lm.com.crt:/etc/nginx/sso.lm.com.crt
      - ./nginx/sso.lm.com.key:/etc/nginx/sso.lm.com.key
      - ./nginx/av2.com.crt:/etc/nginx/av2.com.crt
      - ./nginx/av2.com.key:/etc/nginx/av2.com.key
    depends_on:
      - webapp
      - webapp2
      - keycloak

  webapp:
    image: nginx:1.21-alpine
    container_name: webapp
    volumes:
      - ./webapp:/usr/share/nginx/html

  webapp2:
    image: nginx:1.21-alpine
    container_name: webapp2
    volumes:
      - ./webapp2:/usr/share/nginx/html

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=sso.lm.com
      - KC_PROXY=edge
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
